### PR TITLE
Bump SDK.

### PR DESCRIPTION
**Pull request by robholland**
**What changed?**
Bumped SDK version and made required changes.

**Why?**
To make repo compatible with latest SDK so that code which uses both can compile (tctl for example).

**How did you test it?**
Built tctl with this change.

**Potential risks**
None.

**Is hotfix candidate?**
No.

### CODE REVIEW

**Comment by robholland** [comment]
It seems this needs more work to allow tests to run.

**Comment by yiminc** [comment]
This require some extra work to fix the dependency issue. https://github.com/temporalio/temporal/issues/2597

**Comment by jbreiding** [comment]
This should be possible now if you rebase on master.

**Comment by robholland** [comment]
This is now ready to review. Thanks @jbreiding

**Review by jbreiding — APPROVED** [review]
LGTM

**Pull request merged**
