### PR TITLE
Revert "Remove internal-frontend from default services (#3849)"

### PR DESCRIPTION
**Pull request by MichaelSnowden**
This reverts commit de6f2dfde52bbc7548b3885a9f4506e6b8bd47d8.

**What changed?**
^

**Why?**
It was causing startup issues

**How did you test it?**
Git bisect

**Potential risks**
None

**Is hotfix candidate?**
No

### CODE REVIEW

**Comment by rodrigozhou** [comment]
In this case, I'd rather to fix forward instead of reverting.
cc: @dnr

**Comment by dnr** [comment]
Do https://github.com/temporalio/temporal/pull/3859 instead

**Comment by MichaelSnowden** [comment]
> Do #3859 instead

I'd prefer we do a clean revert because we don't know if that commit will fix the issue, and this is blocking my own development.

**Comment by dnr** [comment]
You can just cherry-pick it in your branch to see if it fixes it. Or rebase your branch to a prior commit. There's no reason for you to be blocked

**Pull request closed without merging**
