### PR TITLE
Add linters goerr113, paralleltest, and tparallel

### PR DESCRIPTION
**Pull request by MichaelSnowden**
**What changed?**
I added the above linters to our .golangci.yml file. This means we will now check for:
1. Dynamic errors like `fmt.Errorf("shard %s lost", key)` which should instead be `fmt.Errorf("%w: %s", ErrShardLost, key)`
2. Bare error comparison like `err1 == err2` instead of using `errors.Is`
3. Tests and subtests that don't call `t.Parallel()`, making tests within a package run sequentially. Improving our existing tests to be parallelizable is likely not going to happen any time soon, but we can at least do our best to fix new tests, and tests within the files we modify in the future. This should be compatible with suite because those usually aren't parallelizable tests, and this check should also ignore suite test methods.
4. Tests that use defer for shutdown instead of `t.Cleanup` which won't work with parallel subtests (see https://stackoverflow.com/a/64178378 )

**Why?**
I recently did a bunch of PR reviews and noticed a lot of violations of these checks, so I think we should automate the process of catching them.

**How did you test it?**
I ran the linters locally and looked at the errors they caught in our existing code, and they made sense to me.

**Potential risks**
This will introduce inconsistencies because there will be new code which follows the guidelines next to old code that doesn't, but we should do our best to leave the file better than we found it and fix those as well.

**Is hotfix candidate?**
No

### CODE REVIEW

**Comment by mmcshane** [comment]
I don't think you want to require t.Parallel() on sub-tests. They certainly _can_ be parallel, but the idomatic way to do multi-test setup is not so much to emulate JUnit with suites but rather to have a parent test that sets up some state and then sub-tests that rely on that initialization. If you have subtests A, B, and C you often want test C to rely on the state changes made in tests A and B

**Comment by MichaelSnowden** [comment]
> I don't think you want to require t.Parallel() on sub-tests. They certainly _can_ be parallel, but the idomatic way to do multi-test setup is not so much to emulate JUnit with suites but rather to have a parent test that sets up some state and then sub-tests that rely on that initialization. If you have subtests A, B, and C you often want test C to rely on the state changes made in tests A and B.

Makes sense; I removed `tparallel`. I think `paralleltest` alone will still catch the true negatives (for loops without the call): https://github.com/kunwardeep/paralleltest#missing-tparallel-in-the-range-method 

> Also, do I understand correctly that if a test is not currently marked t.Parallel() and I trivially modify the file that contains that test then I'm on the hook to make that test and every other one in that file t.Parallel() safe?

You will only get warnings on new (git-based) test functions missing this call. Even if you make changes within an existing test function that is missing this call, you won't get any warnings (unless you rename the function).

**Comment by mmcshane** [comment]
> You will only get warnings on new (git-based) test functions missing this call. Even if you make changes within an existing test function that is missing this call, you won't get any warnings (unless you rename the function).

Okay, thanks, because that would have been untenable.

For me, I wouldn't require T.Parallel() in table-driven tests but I  don't feel as strongly about that.

**Comment by mindaugasrukas** [comment]
If we find those too noisy, we can turn them off.

**Pull request merged**
