### PR TITLE
Update Go SDK to 1.16.0

### PR DESCRIPTION
**Pull request by cretz**
**What changed?**

Update Go SDK

### CODE REVIEW

**Review by yiminc — APPROVED** [review]

**Comment by cretz** [comment]
Build is failing, but doesn't seem related to my change

**Comment by cretz** [comment]
This is on hold because it brings over new events which the server is not prepared for.

**Comment by mmcshane** [comment]
@cretz I just landed #3231 which also updates to 1.16. Sorry - I didn't see this PR until it was too late.

**Comment by cretz** [comment]
@mmcshane - No problem, closing this. Thanks!

**Pull request closed without merging**
