### PR TITLE
Remove tctl code from server

### PR DESCRIPTION
**Pull request by laniehei**
> Describe what has changed in this PR 

Removes any trailing slash that the user inputs to the dc cli command

> Tell your future self why have you made these changes 

It prevents this `https://<someURL>//data-converter/52352` and saves engineers the hours trying to figure out what went wrong.

> How have you verified this change? Tested locally? Added a unit test? Checked in staging env?

I built the tctl plugin and copied it to my path. I then verified that the URL was stripped of the slash. 

> Assuming the worst case, what can be broken when deploying this change to production?

tctl dc could be broken

> Is this PR a hotfix candidate or require that a notification be sent to the broader community? (Yes/No) 

no

### CODE REVIEW

**Review by wxing1292 — APPROVED** [review]

**Comment by yiminc** [comment]
This PR should go to https://github.com/temporalio/tctl. @feedmeapples 1.14 release is published so we should remove tctl code from server repo now.

**Comment by laniehei** [comment]
@yiminc removed tctl code from the temporal server, and updated this PR

**Comment by feedmeapples** [comment]
thanks for the PR

we should keep this PR open for now until we update the pipelines. Ideally would like to switch to github actions https://github.com/temporalio/cicd/issues/533

**Comment by yiminc** [comment]
https://github.com/temporalio/temporal/pull/2461

**Pull request closed without merging**
