### PR TITLE
[proposal #81] Add Open Policy Agent based Authorizer

### PR DESCRIPTION
**Pull request by ghaskins**
# Summary

This patch adds first-class support for [REGO](https://www.openpolicyagent.org/docs/latest/policy-language/) as an Authorizer to augment the current Noop and Default Authorizers, as per [Proposal 81](https://github.com/temporalio/proposals/issues/81).  This feature allows Temporal administrators to define custom Authorizer behavior via configuration at run-time rather than via the [Authorizer plugin](https://docs.temporal.io/security#authorizer-plugin) architecture.

# Usage

By default, this code does nothing.  Users opt into the Authorizer through configuration, as so:

```yaml
global:
  authorizer: opa
```

The default remains the current DefaultAuthorizer as it is today.

## Configuration

Once selecting the OpaAuthorizer, the user can specify one or more REGO policy files.

```yaml
global:
  authorizer: opa
  policies:
    - ...
    - ...
```

Temporal administrators express policies as:

- *Files*: Use "file:path/to/my/policy.rego"
- *Inline*: Use a multi-line yaml string to express a REGO policy
- *Internal Reference*: Administrators reference policies included with Temporal under common/authorization/policies via an 'internal:' prefix, e.g., "internal:default," "internal:noop."

### Default Configuration

Enabling `global.authorizer = opa` without any further configuration is equivalent to the following:

```yaml
global:
  authorizer: opa
  policies:
    - internal:default
```

The `internal:default` policy is intended to be logically equivalent to the current DefaultAuthorizer module written in Golang.

#### Files

```yaml
global:
  authorizer: opa
  policies:
    - file:/etc/temporal/authz/main.rego
    - file:/etc/temporal/authz/utility.rego
```

You may also use any valid [glob pattern](https://pkg.go.dev/path/filepath#Glob):

```yaml
global:
  authorizer: opa
  policies:
    - file:/etc/temporal/authz/*.rego
```

#### Inline

```yaml
global:
  authorizer: opa
  policies:
    - |
      package temporal.authz
      default allow = true
```

#### Internal reference

```yaml
global:
  authorizer: opa
  policies:
    - internal:noop
```

# Policy Details

All policies specified in the configuration will be compiled into one OPA policy bundle and executed as a unit.  The bundling allows the policy author to split more extensive policies into different files for better code organization.  More straightforward policies may use a single document if that is more convenient.

## temporal.authz package

Exactly one policy in the set must implement 'package temporal.authz'.  This namespace accepts an input structure roughly analogous to the inputs of a Golang-based Authorizer interface:

```
input:
  claims:
    System -> (Role):
    Namespaces -> {String, Role}
  target:
    APIName -> String
    Namespace -> String
```

All claims added by the upstream ClaimMapper will also be available.

The policy in 'package temporal.authz' must define a boolean 'allow', where 'true' indicates DecisionAllow and 'false' indicates DecisionDeny.

**How did you test it?**

Unit-tests were added, in addition to extensive testing under the Temporal development flow.

**Potential risks**

Since the code is inert by default and is only activated with explicit operator opt-in, the risk should be very low to the general community.  Users opting to enable the feature are subject to a higher risk, though most of the heavy lifting is accomplished by the Open Policy Agent code base, which is very mature.

**Is hotfix candidate?**

No hotfix necessary:  New feature via explict configuration opt-in only. I'm

### CODE REVIEW

**Comment by anderseknert** [comment]
This is really cool! 😃 Please submit this to the OPA [ecosystem page](https://www.openpolicyagent.org/docs/latest/ecosystem/) once it's made it into a release :)

As for the PR, perhaps another (as in, in addition to what you have) option to consider would be to allow an OPA config file to be provided as an alternative to policy files? That would allow decoupling policy from enforcement, by fetching bundles from (and send decision logs to) remote servers, allow centralized management, independent policy updates, etc. This is basically what the high-level [SDK](https://www.openpolicyagent.org/docs/latest/integration/#integrating-with-the-go-sdk) provides, so should be fairly cheap to add.

**Comment by ghaskins** [comment]
Fix is now merged: https://github.com/open-policy-agent/opa/pull/6062

Scheduled for release in v0.55.0 at the end of July.

**Comment by ghaskins** [comment]
Rebased and updated to latest OPA release.

**Comment by anderseknert** [comment]
No OPA? :(

**Comment by ghaskins** [comment]
Closed for lack of interest.

**Pull request closed without merging**
