### PR TITLE
replace sqlite3 with modernc

### PR DESCRIPTION
**Pull request by jbreiding**
**What changed?**
Replaced sqlite module with pure go implementation

**Why?**
Towards removing CGO run temporal docker images

**How did you test it?**
Local unit tests and sample execution
Added memory and file variant tests for sqlite for future proofing

**Potential risks**
Typical risks with changing persistence dependency modules
The underlying module change does change how connection dsn is built
until schema migration becomes supported there are no implicit backwards compatibility guarantees.

**Is hotfix candidate?**
No

**Build times**
```
vscode ➜ /projects/temporal (master) $ go clean -modcache && go mod download && make clean-bins && time make bins
Delete old binaries...
Delete old binaries...
Build temporal-server with CGO_ENABLED=1 for linux/arm64...
go build -o temporal-server ./cmd/server
Build temporal-cassandra-tool with CGO_ENABLED=1 for linux/arm64...
go build -o temporal-cassandra-tool ./cmd/tools/cassandra
Build temporal-sql-tool with CGO_ENABLED=1 for linux/arm64...
go build -o temporal-sql-tool ./cmd/tools/sql

real    0m5.978s
user    0m7.760s
sys     0m2.080s


vscode ➜ /projects/temporal (master) $ git checkout modernc-sqlite 
Switched to branch 'modernc-sqlite'
Your branch is up to date with 'dev/modernc-sqlite'.
vscode ➜ /projects/temporal (modernc-sqlite) $ go clean -modcache && go mod download && make clean-bins && time CGO_ENABLED=0  make bins
Delete old binaries...
Delete old binaries...
Build temporal-server with CGO_ENABLED=0 for linux/arm64...
go build -o temporal-server ./cmd/server
Build temporal-cassandra-tool with CGO_ENABLED=0 for linux/arm64...
go build -o temporal-cassandra-tool ./cmd/tools/cassandra
Build temporal-sql-tool with CGO_ENABLED=0 for linux/arm64...
go build -o temporal-sql-tool ./cmd/tools/sql

real    0m3.242s
user    0m5.410s
sys     0m1.665s
```

**Canary execution**
image

image

### CODE REVIEW

**Review by wxing1292 — APPROVED** [review]

**Comment by wxing1292** [comment]
Plz try to run go samples / canary locally as sanity tests

**Comment by jlegrone** [comment]
👋 really excited about this!

Heads up that Temporalite supports `synchronous` and `journal_mode` pragmas as of https://github.com/DataDog/temporalite/pull/30. It would be great if those could be validated against the modernc driver as well before merge.

**Comment by jbreiding** [comment]
> 👋 really excited about this!
> 
> Heads up that Temporalite supports `synchronous` and `journal_mode` pragmas as of [DataDog/temporalite#30](https://github.com/DataDog/temporalite/pull/30). It would be great if those could be validated against the modernc driver as well before merge.

Would you be willing to send a PR with a unit/integration test for this case?

**Comment by jlegrone** [comment]
> Would you be willing to send a PR with a unit/integration test for this case?

I don't have bandwidth at the moment, but happy to follow up after this is merged. Before communicating that the sqlite driver is production ready, we should also probably document what level of backwards compatibility we can guarantee for the driver's configuration options.

**Pull request merged**
