### PR TITLE
Allow dynamic config editting outside of container when running docker-compose

### PR DESCRIPTION
**Pull request by vitarb**
This PR introduces a mounted folder with the dynamic config, which is used in the docker-compose startup process.
`DYNAMIC_CONFIG_FILE_PATH` points to the new location of dynamic config on the filesystem.
In case if user changes dynamic config on their machine, changes will also be reflected in the docker container automatically after the next refresh interval.

### CODE REVIEW

**Comment by vitarb** [comment]
> Should we also update Dockerfile? It currently copies over dynamicconfig folder to the generated image:
> 
> ```
> COPY config/dynamicconfig /etc/temporal/config/dynamicconfig
> ```

Do you suggest we should remove it?
I didn't want to touch that part as my goal was for existing docker images to stay the way they are in case if someone runs them directly. Alternatively we could remove this copy and fully rely on mounted files, however this might cause some errors in case if nothing is mounted at all. What do you think?

**Comment by alexshtin** [comment]
I would check what are default values for parameters specified in our default dynamic config and if they are good enough I would remove `COPY` from `Dockerfile`. There is no harm for docker-compose users (which I believe is majority) and those who use docker image directly should be fine with default values.

**Comment by vitarb** [comment]
> I would check what are default values for parameters specified in our default dynamic config and if they are good enough I would remove `COPY` from `Dockerfile`. There is no harm for docker-compose users (which I believe is majority) and those who use docker image directly should be fine with default values.

I agree, it's not dynamic if it's baked into the docker image. My main concern was that someone might be using it already, but probably better to clean it up earlier rather than later.

**Review by underrun — CHANGES_REQUESTED** [review]
If we do this we're assuming a user is running docker-compose from a checked out repo. It might be good to avoid that? or do we expect that this is only useful for development?

Maybe, like `SERVER_TAG`, we can use an env var (`DYNAMIC_CONFIG_PATH`?) with a default of `../config/dynamicconfig` instead of hard coding the relative path?

**Comment by vitarb** [comment]
@underrun yes, docker-compose is used primarily during local development. 
I think there is no harm in making this directory configurable, I've updated the diff to also do that.

**Review by underrun — APPROVED** [review]

**Pull request merged**
