### PR TITLE
Add dynamic config registry and validation

### PR DESCRIPTION
**Pull request by dnr**
## What changed?
Added a process-wide registry for dynamic config settings and perform more validation on file load. Files that were successfully loaded before will still be loaded (for now), but more warnings may be logged. Eventually we can make some of the checks stricter.

Added a top-level CLI command to validate dynamic config files.

## Why?
Catch more errors, set up structure for doc generation and user-defined validation.

## How did you test it?
unit tests

### CODE REVIEW

**Comment by bergundy** [comment]
Does this assume that all the dynamic configs are in `dynamicconfig/constants.go`?
We have configs in components that aren't defined there. Does the CLI need to import all of the components for this to work? Ideally it shouldn't need to know about them but we may just need to import them to unblock this work.

**Comment by dnr** [comment]
> Does this assume that all the dynamic configs are in `dynamicconfig/constants.go`?

No, just that they're created in static initializers.

> We have configs in components that aren't defined there. Does the CLI need to import all of the components for this to work? Ideally it shouldn't need to know about them but we may just need to import them to unblock this work.

What's the interaction with the CLI? This is a server thing... the CLI embeds a server, the server somehow or other imports all the components, right? If it doesn't import a component then how can it use it?

**Comment by bergundy** [comment]
> > We have configs in components that aren't defined there. Does the CLI need to import all of the components for this to work? Ideally it shouldn't need to know about them but we may just need to import them to unblock this work.
> 
> What's the interaction with the CLI? This is a server thing... the CLI embeds a server, the server somehow or other imports all the components, right? If it doesn't import a component then how can it use it?

By CLI I mean the server entrypoint where this new subcommand is registered. As long as this entrypoint contains all node roles we should get coverage for all registered components.

**Comment by dnr** [comment]
> By CLI I mean the server entrypoint where this new subcommand is registered. As long as this entrypoint contains all node roles we should get coverage for all registered components.

It's the main package, that starts the server. If it's not linked in there, it can't possibly run.

But the cli isn't the main point, that's just a little example to demonstrate things. The main value is in server logs, and in control-plane applications that import the server as a library and call ValidateFile (which will need to link in everything they use, yes)

**Comment by bergundy** [comment]
> > By CLI I mean the server entrypoint where this new subcommand is registered. As long as this entrypoint contains all node roles we should get coverage for all registered components.
> 
> It's the main package, that starts the server. If it's not linked in there, it can't possibly run.
> 
> But the cli isn't the main point, that's just a little example to demonstrate things. The main value is in server logs, and in control-plane applications that import the server as a library and call ValidateFile (which will need to link in everything they use, yes)

I just worry that authors of these tools will assume all dynamic configs are in a single file and will miss validation.
We may need to continue putting all of the configs in the monolithic file and revert the new component structure but there are alternatives that can help support the new structure.

**Comment by dnr** [comment]
> I just worry that authors of these tools will assume all dynamic configs are in a single file and will miss validation. We may need to continue putting all of the configs in the monolithic file and revert the new component structure but there are alternatives that can help support the new structure.

I don't think it's that big of a deal. We can just make a package that imports all the components. We need that to import them from main anyway, right?

Unknown keys just show up as warnings. It should be pretty obvious to whoever is handling these warnings what's going on.

**Review by bergundy — APPROVED** [review]

**Pull request merged**
