### PR TITLE
Enable gRPC reflection for frontend service

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
[gRPC reflection](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) was enabled for frontend service.
****Unfortunately, [gogo doesn't support it](https://jbrandhorst.com/post/gogoproto/) and the only API that works is [health check API](https://github.com/grpc/grpc/blob/master/doc/health-checking.md).****

**Why?**
gRPC reflection allows standrat gRPC tools like `grpc_cli`, `grpcurl`, `evans` to make RPC calls easily.
Here is how to do it with [evans](https://github.com/ktr0731/evans):
```bash
$ echo '{"service":"temporal.api.workflowservice.v1.WorkflowService"}' | evans --host 127.0.0.1 --port 7233 --reflection cli call grpc.health.v1.Health.Check

{
  "status": "SERVING"
}
```

**How did you test it?**
Run some tools to see health service response.

**Potential risks**
No risks.

### CODE REVIEW

**Comment by sergeybykov** [comment]
Why?

**Comment by pquerna** [comment]
unsure of @alexshtin use case, but It makes using grpccurl easier: https://github.com/fullstorydev/grpcurl#grpcurl

**Comment by alexshtin** [comment]
Yeah, I was in progress of writing description.

**Comment by wxing1292** [comment]
Will there be any security concern? 

Is the reflection only used for health check?

**Comment by alexshtin** [comment]
I wish it would work for everything but gogo doesn't generate required code. But even if it does what can be that security concern? Those are public well described interfaces and all the tools I listed above can be used w/o reflection. Just path to proto files (which are public) needs to be passed explicitly.

**Comment by wxing1292** [comment]
> I wish it would work for everything.

The only real use case i can imagine is health check. and seems that currently only health check is exposed

**Review by wxing1292 — APPROVED** [review]

**Comment by alexshtin** [comment]
It would be nice to do any admin operation, or visibility requests, or even start workflow w/o `tctl` but with any gRPC tool of user choice. `evans` btw, has nice UI in REPL mode.

**Comment by wxing1292** [comment]
> It would be nice to do any admin operation, or visibility requests, or even start workflow w/o `tctl` but with any gRPC tool of user choice. `evans` btw, has nice UI in REPL mode.

any non dev related API calls should use the proto file / proto generated code, or otherwise there will be one additional round trip to just fetch the metadata of the APIs?

**Comment by alexshtin** [comment]
I think tools do it once before first call. Basically yes, instead of using local file it downloads it from server itself.

**Pull request merged**
