### PR TITLE
add optional explicit ForceTLS option to ClientTLS config

### PR DESCRIPTION
**Pull request by thewmo**
**What changed?**
Add an optional `useTls` config property under `publicClient` to override whether or not TLS is used when connecting to the endpoint, regardless of the `tls.frontend.server` configuration.

**Why?**
To fix issue 2035, which I encountered while setting up Temporal under ECS in AWS with a frontend ALB load balancer terminating TLS.

**How did you test it?**
Tested locally and in my nonproduction environment.

**Potential risks**
Worker role may fail to start if property is incorrectly set. Not setting the property at all results in the status quo behavior where TLS is based on configuration present in `tls.frontend.server`.

**Is hotfix candidate?**
No

Note that I'm a newb to golang and am more than open to recommendations here.

### CODE REVIEW

**Comment by thewmo** [comment]
@sergeybykov Thank you for reviewing my PR. Apologies that I based it off the commit tagged `1.12.2`, I did that for my own dev purposes but it made for a messy pull request.

I definitely can see that a solution that doesn't change the interface of `TLSConfigProvider` is desirable; that is the main thing I didn't like about mine. I think my only concern with the `SystemWorker` proposal is that, for a user in an environment that has an installed system-level set of CA certs (where Golang will find the cert on its own) they still need some way to tell the server "this endpoint is a TLS endpoint". (But maybe Temporal server doesn't support system-installed root certs?)

One option might be adding an explicit `isEnabled` option to the `ClientTLS` struct so the user can say "use TLS here even though I don't need to configure anything out of the ordinary". Part of the issue here is that whether or not an endpoint is TLS is logically a property of the endpoint and so having it in the "custom TLS" config is maybe problematic. If the `HostPort` supported the `grpcs://` prefix that might be another way to go, though I don't know GRPC well enough to say.

Thanks again for looking at this, I have no objection to whatever you all ultimately decide to do, so long as I can configure the worker client to use TLS without having the frontend running TLS. :-)

**Comment by sergeybykov** [comment]
>I think my only concern with the SystemWorker proposal is that, for a user in an environment that has an installed system-level set of CA certs (where Golang will find the cert on its own) they still need some way to tell the server "this endpoint is a TLS endpoint".  (But maybe Temporal server doesn't support system-installed root certs?)

I feel that I'm missing something here. Please help me understand.
System-level root certs are used if installed for checking client and server certs, but only to make sure they are valid. On top of that, server uses `ServerTLS.ClientCAFiles` or `ServerTLS.ClientCAData` to restrict what clients can connect to it, so that only client certs signed by the specified client CAs are accepted. I don't see how these settings can be implicitly set via the system-level set of CA certs. Otherwise, a client with any valid cert issues by those CAs would be able to connect. This is where I lost your point about environment.

Similarly, on the client side (system worker is a client) we need to tell it what certificate and key to use for connecting to the frontend. My thinking was that if we change the code to use TLS for system worker whenever `SystemWorker` properties are set, regardless of the server TLS configuration, then system worker will be able to connect to the ALB even if server TLS is not set at all. But maybe we just need to change
```
s.settings.Frontend.IsEnabled()
```
[here](https://github.com/temporalio/temporal/blob/f8cc50abcb6b0ee84108761e1f29592be06f4dc3/common/rpc/encryption/localStoreTlsProvider.go#L157) to an equivalent of 
```
client.IsEnabled()
```

Is this similar to what you meant by the following sentence? Would this resolve the issue for you?
>One option might be adding an explicit isEnabled option to the ClientTLS struct so the user can say "use TLS here even though I don't need to configure anything out of the ordinary".

Then I lost you again on
>Part of the issue here is that whether or not an endpoint is TLS is logically a property of the endpoint and so having it in the "custom TLS" config is maybe problematic. If the HostPort supported the grpcs:// prefix that might be another way to go, though I don't know GRPC well enough to say.

If you like, we can do a quick Zoom call to clear my misunderstanding. 

Can you rebase this on top of the latest master? I can help with that if needed.

**Comment by sergeybykov** [comment]
@thewmo For some reason, I don't have permissions to push to your branch. Can you take a look and merge from [my branch](https://github.com/sergeybykov/temporal/commits/2035-explicit-tls)?

**Comment by thewmo** [comment]
@sergeybykov this looks good to me. I don't know why you couldn't push to my branch, I do have the "allow maintainers..." box checked. I went ahead and invited you explicitly to my repo. Feel free to push to it, or I will pull your branch when I'm back in front of my work computer.

**Pull request merged**
