### PR TITLE
Remove dummy registrations in sdk integration test

### PR DESCRIPTION
**Pull request by dnr**
**What changed?**
Remove dummy registrations that aren't needed anymore.

**Why?**
They can cause name conflicts with other tests that use anonymous functions as workflows/activities.

**How did you test it?**
they are tests

**Potential risks**

**Is hotfix candidate?**

### CODE REVIEW

**Comment by yiminc** [comment]
Do you observe conflict? The SetupTest() would re-create worker for each test and registration is per worker, so it should not have problem.

**Comment by dnr** [comment]
> Do you observe conflict? The SetupTest() would re-create worker for each test and registration is per worker, so it should not have problem.

It was breaking my cron test rewrite until I gave it an explicit name. To test the theory, I rearranged code in the existing tests and got one of them to conflict too. I didn't look into how the worker is recreated so I don't fully understand it either

**Review by yiminc — APPROVED** [review]
it is worth to spend sometime understand why it could happen, each worker should have their own registry.

**Comment by dnr** [comment]
I investigated a little more. I think the problem is that clientIntegrationSuite.SetupTest registers a dummy workflow and activity, and those were getting registered with names `func1` and `func2`, which are easy to conflict with anonymous workflow and activity functions in the actual tests. Even if I add a RegisterOptions to those calls, it still conflicts, since the sdk still keeps the actual function names as aliases.

If I remote the dummy registrations entirely, the tests pass for me, though. It looks you added them in #1934. Do you remember why they were needed? If they are needed after all, I think the best option would be to make them top-level functions.

**Comment by yiminc** [comment]
@dnr we can remove the dummy func registration. They were added because the SDK would skip worker start if no func was registered. That has been changed in SDK so you could start worker without registration and add registration later after start. It is safe to remove them now.

**Pull request merged**
