### PR TITLE
Code style fix

### PR DESCRIPTION
**Pull request by mindaugasrukas**
**What changed?**
Don't create an intermediate variable

Used [gopatch](https://github.com/uber-go/gopatch) for automation:

`return_err.patch`:
```
@@
@@
-err := ...
-return err
+return ...
```

Commands:
```
% gopatch -p return_err.patch ./...
```

**Why?**
Code style fix.

**How did you test it?**

**Potential risks**

**Is hotfix candidate?**

### CODE REVIEW

**Review by MichaelSnowden — APPROVED** [review]
This looks great, thank you! As a bonus, could you see if there's a `golangci-lint` rule for this? Something like "redundant err declaration" or "inline err return".

**Comment by mindaugasrukas** [comment]
> This looks great, thank you! As a bonus, could you see if there's a `golangci-lint` rule for this? Something like "redundant err declaration" or "inline err return".

Let me check.

**Comment by mindaugasrukas** [comment]
I can't find anything related in the golangci-lint.

**Comment by MichaelSnowden** [comment]
> I can't find anything related in the golangci-lint.

Hmm, ok. I'll take a closer look because it would be a shame if we fix these style issues now but they crop up again later. The config is probably buried in one of the nested linters' documentation.

**Comment by MichaelSnowden** [comment]
> > I can't find anything related in the golangci-lint.
> 
> Hmm, ok. I'll take a closer look because it would be a shame if we fix these style issues now but they crop up again later. The config is probably buried in one of the nested linters' documentation.

Unfortunately, I couldn't find one in a reasonable amount of time.

**Pull request merged**
