### PR TITLE
Add cluster-aware quota limits for concurrent long-running requests

### PR DESCRIPTION
**Pull request by MichaelSnowden**
**What changed?**
I added some cluster-aware limits on the number of concurrent long-running requests and namespace-replication-inducing requests. I also did a lot of refactoring and added a bunch of documentation around here to make this clearer because the "namespace count" terminology was not very descriptive.

**Why?**
These limits are designed to protect database resources, so if we just use the per-instance limits, we could end up with a total limit which is very high when there are many instances, or, conversely, too low if there are few instances.

**How did you test it?**
I added unit tests.

**Potential risks**

**Is hotfix candidate?**

### CODE REVIEW

**Comment by yux0** [comment]
What is the difference between GlobalNamespaceReplicationInducingAPIsRPS and GlobalNamespaceNamespaceReplicationInducingAPIsRPS?

**Comment by MichaelSnowden** [comment]
> What is the difference between GlobalNamespaceReplicationInducingAPIsRPS and GlobalNamespaceNamespaceReplicationInducingAPIsRPS?

This was a mistake. There should only be one. I left the old one and removed the new one

**Review by yycptt — COMMENTED** [review]
I don't think ns count limit is for protecting DB resource. I am under the impression that those limit exists to protect resources like network connections, file descriptors on a host.

**Comment by MichaelSnowden** [comment]
> I don't think ns count limit is for protecting DB resource. I am under the impression that those limit exists to protect resources like network connections, file descriptors on a host. But please correct me if I am wrong.

This makes sense to me. I'm going to close this

**Comment by MichaelSnowden** [comment]
I'm keeping the refactoring changes though and putting them in a separate PR here: https://github.com/temporalio/temporal/pull/4665

**Pull request closed without merging**
