### PR TITLE
Fix schema loading for mysql and cassandra persistence tests 

### PR DESCRIPTION
**Pull request by markmark206**
(best reviewed with "Hide whitespace changes" option enabled).
**What changed?**
When cassandra and mysql persistence tests load db schema, they assume that the repo is cloned into the folder named "temporal" (and also that the path to that folder does not include segments containing `temporal`, but that's another issue).

This breaks if the folder is NOT named "temporal". The cause of the failure is not obvious by looking at the failure message.

This change allows for specifying the path to the repo's root in an environment variable, `TEMPORAL_ROOT`, and panic'ing if the environment variable is not set AND the repo is not cloned into a path that includes "temporal" segment.

This codebase has significant code duplication, and I resisted the urge to spend time on more involved refactoring.

**Why?**
I made this change because I cloned the repo into a folder other than "temporal" and wasn't able to run tests because of that, and spent some time figuring out why.

**How did you test it?**

1. I ran tests 

```
~/src/temporal-mm $ TEMPORAL_ROOT=~/src/temporal-mm make unit-test
...
```
and made sure the schemas got loaded as expected.

2. I ran tests without specifying TEMPORAL_ROOT and watched the panic:

```
~/src/temporal-mm $ make unit-test
....
--- FAIL: TestCassandraHistoryV2Persistence (0.21s)
panic: Unable to find repo path. Use env var TEMPORAL_ROOT or clone the repo into folder named 'temporal' [recovered]
	panic: Unable to find repo path. Use env var TEMPORAL_ROOT or clone the repo into folder named 'temporal'
```
3. I didn't test running from `~/src/temporal`, without specifying `TEMPORAL_ROOT`, so I didn't verify that the existing behavior continues to work, relying on my colleagues with that setup to tell me if this breaks. ;)
 

**Potential risks**
The risk is that tests break. In which case, I will fix them or rollback the change.

### CODE REVIEW

**Comment by markmark206** [comment]
Great, thank you for taking a look!

Updated references to `cadence ` to `temporal`.

Using `go.mod` to locate the root of the repo seems clever, but I am a bit concerned that we are setting ourselves up for another `/User/maschema/...` event down the road, if `go.mod` semantics (and/or our clever usage of it) change at some point. So I think my current preference would be for a more explicit indicator mechanism (hence the explicit `TEMPORAL_ROOT` env var).

Thoughts?

**Comment by alexshtin** [comment]
I am all for `TEMPORAL_ROOT` env. I am just saying that default value (in case it env is missed) should be better based on `go.mod` rather than name `temporal`. Another option for marker is `.git` dir but it might won't work if we migrate to mono repo one day in the future.

**Comment by markmark206** [comment]
Ah, yes, great point.

In the interest of code velocity, and to reduce the risk of regressions/negative impact on developers, I propose tracking the improvements to how we auto-identify the path as a separate ticket.

Thoughts?

**Comment by alexshtin** [comment]
Yes, let's create an issue and link it to this PR.

**Pull request merged**
