### PR TITLE
Only unload TaskQueueManager if ownership is lost or queue traffic drops

### PR DESCRIPTION
**Pull request by mmcshane**
**What changed?**
Where previously any error from the task storage subsystem during task
ID block acquisition would cause the taskQueueManagerImpl to unload
itself, we now explicitly test for the ConditionFailedError that
indicates another TaskQueueManager has taken ownership of this queue
partition. As a result, a TaskQueueManager can now stay active during a
storage availability event and continue to perform sync-matching. Queue
unloading due to liveness timeouts continues to operate as previous - 
absence of pollers and tasks for a configured period (default=5m) will still
unload the queue.

**Why?**
We'd like for matching availability to be > storage availability

**How did you test it?**
New unit tests. Manual fault injection tests in progress

**Potential risks**
Task ID corruption

**Is hotfix candidate?**
No

### CODE REVIEW

**Review by yiminc — COMMENTED** [review]
lgtm, please finish manual test to verify the work.
Also, we unload not only when lost ownership, but also on idle. So maybe update the title and description to point that out. Please also manually verify that idle unload logic is not changed.

**Comment by mmcshane** [comment]
Doesn't work in practice. When Matching loses connectivity to C* it immediately stops dispatching tasks. Still investigating but I'm going to close this as there will obviously be further changes needed.

**Comment by mmcshane** [comment]
I was wrong, this works. More or less. If sync-match misses (which is subject to the Poll duration and frequency of the worker) then the task "spills" to storage which fails (intentionally in this test) and the AddTask RPC returns an error. In these cases I wasn't waiting long enough for the History-side retry to kick in and retransmit the task. With enough time the task retransmits into an AddTask that finds a sync-match partner and eventually works.

From the client side it looks like random workflow latency spikes. Some tasks are dispatched immediately and some have to go through multiple retransmit rounds.

Testing methodology
1. Run the standard server dependencies with `make start-dependencies`
2. Start a server process running everything except matching `./temporal-server start --service frontend --service history --service worker`
3. Clone the development.yaml file to development-temp.yaml and set a non-default cassandra port number in the latter (`port: 9041` under persistence/datastores/cass-default/cassandra)
4. Proxy the non-default port from previous step to the default port, 9042. `socat tcp-listen:9041,reuseaddr,fork tcp:localhost:9042`
5. Start a server process running just matching and using the augmented config file `./temporal-server --env development-temp start --service matching`

With the above setup you can partition just the matching service away from Cassandra by killing/restarting (or SIGSTOP/SIGCONT) the `socat` proxy process.

Note that a crashed matching service process cannot recover until database connectivity is restored as it refuses to start up if it is unable to ascertain and validate the database schema version

**Review by yiminc — APPROVED** [review]
One more simple test worth to try out: simply drop the tasks table from cass. Verify server could still start, and sync match still happening.

**Comment by mmcshane** [comment]
Confirmed that sync-match works with the `temporal.tasks` table having been dropped

**Pull request merged**
