### PR TITLE
Remove namespace field from ScheduleActivityTaskCommandAttributes message

### PR DESCRIPTION
**Pull request by alexshtin**
**What changed?**
Remove `namespace` field from `ScheduleActivityTaskCommandAttributes` message.

**Why?**
To remove ability of cross namespace activity calls.
See https://github.com/temporalio/api/pull/174 for more details.

**How did you test it?**
Existing tests.

**Potential risks**
Low risk: `namespace` field is not exposed for the most SDKs but there might be some unofficial SDK which will loose ability to start activity in another namespace.

**Is hotfix candidate?**

### CODE REVIEW

**Review by yycptt — APPROVED** [review]
Do you plan to update history activity transfer task definition and matching AddActivityTask request as well?

**Review by yycptt — APPROVED** [review]
👍

**Review by yycptt — COMMENTED** [review]
Will there be any backward/forward compatibility issues when rolling out the change?

**Comment by alexshtin** [comment]
> Will there be any backward/forward compatibility issues when rolling out the change?

Good point. Now it does!

**Review by yycptt — APPROVED** [review]

**Comment by yycptt** [comment]
Some more context for what we are trying to do here.
In the next release (1.17), we will continue to write to
- target namespaceID in transfer activity task,
- namespaceID in activityInfo
- sourceNamespaceID in addActivityTask request

But no logic will use those three fields. And in 1.18 those write logic can also be removed.

**Pull request merged**
